trigger:
  batch: true
  branches:
    include:
    - '*'

jobs:

- job: 'Test'
  strategy:
    matrix:
      Python27Linux:
        imageName: 'ubuntu-16.04'
        python.version: '2.7'
      Python27Mac:
        imageName: 'macos-10.13'
        python.version: '2.7'
      Python35Linux:
        imageName: 'ubuntu-16.04'
        python.version: '3.5'
      Python35Windows:
        imageName: 'vs2017-win2016'
        python.version: '3.5'
      Python35Mac:
        imageName: 'macos-10.13'
        python.version: '3.5'
      Python36Linux:
        imageName: 'ubuntu-16.04'
        python.version: '3.6'
      Python36Windows:
        imageName: 'vs2017-win2016'
        python.version: '3.6'
      Python36Mac:
        imageName: 'macos-10.13'
        python.version: '3.6'
      Python37Linux:
        imageName: 'ubuntu-16.04'
        python.version: '3.7'
      Python37Windows:
        imageName: 'vs2017-win2016'
        python.version: '3.7'
      Python37Mac:
        imageName: 'macos-10.13'
        python.version: '3.7'
    maxParallel: 4
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      source ./travis/before_install_linux.sh
      before_install
    condition: eq( variables['Agent.OS'], 'Linux')
    displayName: 'Preinstall (Linux)'

  - script: |
      #source ./travis/before_install_osx.sh
      #before_install
    condition: eq( variables['Agent.OS'], 'Darwin')
    displayName: 'Preinstall (Mac)'

  - script: |
      python -m pip install --upgrade pip wheel
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: python setup.py bdist_wheel
    displayName: 'Build wheel'

  - script: |
      choco install llvm
      cd ..
      bash -c "cp -r $(Agent.BuildDirectory) /c/build"
      bash -lc "python -m pip install /c/build/dist/*.whl"
    condition: eq( variables['Agent.OS'], 'Windows_NT')
    displayName: 'Install wheel (Windows)'

  - script: |
      rm -rf blis*
      python -m pip install dist/*.whl
    condition: in( variables['Agent.OS'], 'Linux', 'Darwin')
    displayName: 'Install wheel (Linux, Mac)'

  - script: |
      python -m pytest --pyargs blis
    displayName: 'Run tests'
