trigger:
  batch: true
  branches:
    include:
    - '*'

variables:
  # Change this to generate JSONL / headers instead of running a normal build
  generate_jsonl: true

jobs:
- job: 'JSONL'
  condition: eq(variables['generate_jsonl'], 'true')
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
    git submodule update --init --recursive
    cp azure_files/build.sh flame-blis
    cd flame-blis
    set MSYSTEM=MINGW%ARCH%
    set MSYS2_PATH_TYPE=inherit
    set CHERE_INVOKING=1
    FOR /F "delims=" %%i in ('cygpath.exe -u "%PREFIX%"') DO set "PREFIX=%%i"
    FOR /F "delims=" %%i in ('cygpath.exe -u "%BUILD_PREFIX%"') DO set "BUILD_PREFIX=%%i"
    bash -lce "./build.sh"
    if errorlevel 1 exit 1
  displayName: 'Build'

  - task: CopyFiles@2
    inputs:
      contents: $(Build.SourcesDirectory)/blis/_src/make/windows-x86_64.jsonl
      targetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true
    displayName: 'Copy JSONL'

  - task: CopyFiles@2
    inputs:
      contents: $(Build.SourcesDirectory)/flame-blis/make.log
      targetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true
    displayName: 'Copy make.log'

  - task: CopyFiles@2
    inputs:
      contents: $(Build.SourcesDirectory)/flame-blis/include/x86_64/blis.h
      targetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true
    displayName: 'Copy header'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: data
    displayName: 'Publish JSONL'

- job: 'Test'
  condition: eq(variables['generate_jsonl'], 'false')
  strategy:
    matrix:
      # Python27Linux:
      #   imageName: 'ubuntu-16.04'
      #   python.version: '2.7'
      # Python27Mac:
      #   imageName: 'macos-10.13'
      #   python.version: '2.7'
      # Python35Linux:
      #   imageName: 'ubuntu-16.04'
      #   python.version: '3.5'
      # Python35Mac:
      #   imageName: 'macos-10.13'
      #   python.version: '3.5'
      # Python36Linux:
      #   imageName: 'ubuntu-16.04'
      #   python.version: '3.6'
      # Python36Mac:
      #   imageName: 'macos-10.13'
      #   python.version: '3.6'
      # Python37Linux:
      #   imageName: 'ubuntu-16.04'
      #   python.version: '3.7'
      # Python37Mac:
      #   imageName: 'macos-10.13'
      #   python.version: '3.7'
      # Python38Linux:
      #   imageName: 'ubuntu-16.04'
      #   python.version: '3.8'
      Python38Windows:
        imageName: 'vs2017-win2016'
        python.version: '3.8'
      # Python38Mac:
      #   imageName: 'macos-10.13'
      #   python.version: '3.8'
    maxParallel: 4
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      source ./travis/before_install_linux.sh
      before_install
    condition: eq( variables['Agent.OS'], 'Linux')
    displayName: 'Preinstall (Linux)'

  - script: |
      python -m pip install --upgrade pip wheel
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: python setup.py bdist_wheel
    displayName: 'Build wheel'

  - script: |
      choco install llvm
      cd ..
      bash -c "cp -r $(Agent.BuildDirectory) /c/build"
      bash -lc "python -m pip install /c/build/dist/*.whl"
    condition: eq( variables['Agent.OS'], 'Windows_NT')
    displayName: 'Install wheel (Windows)'

  - script: |
      rm -rf blis*
      python -m pip install dist/*.whl
    condition: in( variables['Agent.OS'], 'Linux', 'Darwin')
    displayName: 'Install wheel (Linux, Mac)'

  - script: |
      python -m pytest --pyargs blis
    displayName: 'Run tests'
