trigger:
  batch: true
  branches:
    include:
    - '*'

jobs:
- job: 'Test'
  strategy:
    matrix:
      # Python27Linux:
      #   imageName: 'ubuntu-16.04'
      #   python.version: '2.7'
      # Python27Mac:
      #   imageName: 'macos-10.13'
      #   python.version: '2.7'
      # Python35Linux:
      #   imageName: 'ubuntu-16.04'
      #   python.version: '3.5'
      # Python35Mac:
      #   imageName: 'macos-10.13'
      #   python.version: '3.5'
      # Python36Linux:
      #   imageName: 'ubuntu-16.04'
      #   python.version: '3.6'
      # Python36Mac:
      #   imageName: 'macos-10.13'
      #   python.version: '3.6'
      # Python37Linux:
      #   imageName: 'ubuntu-16.04'
      #   python.version: '3.7'
      # Python37Mac:
      #   imageName: 'macos-10.13'
      #   python.version: '3.7'
      # Python38Linux:
      #   imageName: 'ubuntu-16.04'
      #   python.version: '3.8'
      Python38Windows:
        imageName: 'vs2017-win2016'
        python.version: '3.8'
      # Python38Mac:
      #   imageName: 'macos-10.13'
      #   python.version: '3.8'
    maxParallel: 4
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      source ./travis/before_install_linux.sh
      before_install
    condition: eq( variables['Agent.OS'], 'Linux')
    displayName: 'Preinstall (Linux)'

  - script: choco install llvm
    condition: eq( variables['Agent.OS'], 'Windows_NT')
    displayName: 'Preinstall (Windows)'

  - script: |
      python -m pip install --upgrade pip wheel
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      set "PATH=C:\Program Files\LLVM\bin;%PATH%"
      ls "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC"
      clang --version
      python setup.py bdist_wheel
    condition: eq( variables['Agent.OS'], 'Windows_NT')
    displayName: 'Build wheel (Windows)'

  - script: python setup.py bdist_wheel
    condition: or(eq(variables['Agent.OS'], 'Linux'), eq(variables['Agent.OS'], 'Darwin'))
    displayName: 'Build wheel (Linux / Mac)'

  - bash: |
      rm -rf blis*
      python -m pip install dist/*.whl
    displayName: 'Install wheel'

  - script: |
      python -m pytest --pyargs blis
    displayName: 'Run tests'
